spring:
  datasource:
    username: entkegiu
    url: jdbc:postgresql://salt.db.elephantsql.com:5432/entkegiu
    password: 15sPN0-TmXBlxUUadWED0o2bmhSW1a__
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true '
    show-sql: 'false'
    hibernate:
      ddl-auto: none
  database:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgresql
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.letscode.modulobanco811.jms.TransferenciaMsgDeserializer
      group-id: group_id


auto:
  create:
    topics:
      enable: true

kafka:
  topic:
    name: banco811.example.topic
